name: "Build"
on:
  push:
    branches:
      - '*'
    paths:
      - '*.sh'
      - '.github/workflows/build.yml'
      - '*.txt'
      - 'conf/*'

  release:
    types: [ created ]


jobs:
  build:
    strategy:
      matrix:
        os: ["12.3", "13.0", "13.1"]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - run: |
        bash build.sh conf/freebsd-${{ matrix.os }}.conf
    - name: Get release
      if: "contains(github.ref, 'refs/tags/')"
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Release Asset
      if: "contains(github.ref, 'refs/tags/')"
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./freebsd-${{ matrix.os }}.ova.7z
        asset_name: freebsd-${{ matrix.os }}.ova.7z
        asset_content_type: application/x-7z-compressed


