name: "Build"
on:
  push:
    branches:
      - '*'
    paths:
      - '*.sh'
      - '.github/workflows/build.yml'
      - '*.txt'
      - 'conf/*'

  release:
    types: [ created ]


jobs:
  build:
    strategy:
      matrix:
        os: ["12.3", "13.0", "13.1"]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - run: |
        bash build.sh conf/freebsd-${{ matrix.os }}.conf
    - name: Get release
      if: "contains(github.ref, 'refs/tags/')"
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Release Asset
      if: "contains(github.ref, 'refs/tags/')"
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          freebsd-${{ matrix.os }}.ova.zip
          freebsd-${{ matrix.os }}-id_rsa.pub
          freebsd-${{ matrix.os }}-mac.id_rsa


